import React from 'react';

export default function ColorMatrix() {
  return (
    <div className="max-w-[1440px] mx-auto px-4 md:px-8 py-8">
      <div className="space-y-12">
        <div>
          <div className="mb-8 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h2 className="text-lg font-black tracking-tighter uppercase font-heading">MATRIZ DE CORES DE PRODUÇÃO</h2>
              <p className="mt-2 text-sm text-muted-foreground">Combinações documentadas de variantes × cores com contagens de produção, incluindo quaisquer lacunas observadas ou registros não atribuídos.</p>
            </div>
            <span className="badge-confidence confidence-confirmed"><span className="w-1.5 h-1.5 rounded-full bg-foreground"></span>confirmed</span>
          </div>
          <div className="border border-border bg-card p-4 overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full border-collapse text-xs">
                <thead>
                  <tr>
                    <th className="sticky left-0 z-10 bg-card px-3 py-2 text-left font-normal text-muted-foreground w-40">Model</th>
                    <th className="px-1 py-2 text-center font-normal"><div className="mx-auto mb-1 h-3.5 w-3.5 border border-foreground/10" style={{ background: 'rgb(204, 43, 30)' }}></div><div className="text-[10px] text-muted-foreground">AR2</div></th>
                    <th className="px-1 py-2 text-center font-normal"><div className="mx-auto mb-1 h-3.5 w-3.5 border border-foreground/10" style={{ background: 'rgb(245, 208, 0)' }}></div><div className="text-[10px] text-muted-foreground">EV1</div></th>
                    <th className="px-1 py-2 text-center font-normal"><div className="mx-auto mb-1 h-3.5 w-3.5 border border-foreground/10" style={{ background: 'rgb(138, 122, 60)' }}></div><div className="text-[10px] text-muted-foreground">EY0</div></th>
                    <th className="px-1 py-2 text-center font-normal"><div className="mx-auto mb-1 h-3.5 w-3.5 border border-foreground/10" style={{ background: 'rgb(42, 42, 42)' }}></div><div className="text-[10px] text-muted-foreground">GV1</div></th>
                    <th className="px-1 py-2 text-center font-normal"><div className="mx-auto mb-1 h-3.5 w-3.5 border border-foreground/10" style={{ background: 'rgb(45, 92, 60)' }}></div><div className="text-[10px] text-muted-foreground">JW0</div></th>
                    <th className="px-1 py-2 text-center font-normal"><div className="mx-auto mb-1 h-3.5 w-3.5 border border-foreground/10" style={{ background: 'rgb(176, 176, 176)' }}></div><div className="text-[10px] text-muted-foreground">KR4</div></th>
                    <th className="px-1 py-2 text-center font-normal"><div className="mx-auto mb-1 h-3.5 w-3.5 border border-foreground/10" style={{ background: 'rgb(154, 172, 184)' }}></div><div className="text-[10px] text-muted-foreground">KV2</div></th>
                    <th className="px-1 py-2 text-center font-normal"><div className="mx-auto mb-1 h-3.5 w-3.5 border border-foreground/10" style={{ background: 'rgb(123, 79, 140)' }}></div><div className="text-[10px] text-muted-foreground">LV4</div></th>
                    <th className="px-1 py-2 text-center font-normal"><div className="mx-auto mb-1 h-3.5 w-3.5 border border-foreground/10" style={{ background: 'rgb(90, 58, 122)' }}></div><div className="text-[10px] text-muted-foreground">LX0</div></th>
                    <th className="px-1 py-2 text-center font-normal"><div className="mx-auto mb-1 h-3.5 w-3.5 border border-foreground/10" style={{ background: 'rgb(240, 240, 240)' }}></div><div className="text-[10px] text-muted-foreground">QM1</div></th>
                    <th className="px-1 py-2 text-center font-normal"><div className="mx-auto mb-1 h-3.5 w-3.5 border border-foreground/10" style={{ background: 'rgb(232, 224, 208)' }}></div><div className="text-[10px] text-muted-foreground">QT1</div></th>
                    <th className="px-1 py-2 text-center font-normal"><div className="mx-auto mb-1 h-3.5 w-3.5 border border-foreground/10" style={{ background: 'rgb(220, 220, 208)' }}></div><div className="text-[10px] text-muted-foreground">QX1</div></th>
                    <th className="px-1 py-2 text-center font-normal"><div className="mx-auto mb-1 h-3.5 w-3.5 border border-foreground/10" style={{ background: 'rgb(58, 108, 176)' }}></div><div className="text-[10px] text-muted-foreground">TV2</div></th>
                    <th className="px-1 py-2 text-center font-normal"><div className="mx-auto mb-1 h-3.5 w-3.5 border border-foreground/10" style={{ background: 'rgb(192, 192, 184)' }}></div><div className="text-[10px] text-muted-foreground">WV2</div></th>
                    <th className="px-3 py-2 text-right font-normal text-muted-foreground w-16">Total</th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="bg-secondary"><td className="sticky left-0 z-10 bg-secondary px-3 py-1.5 font-bold text-[10px] uppercase tracking-wider">Series 1</td><td colSpan="14"></td><td className="px-3 py-1.5 text-right font-bold">7,066</td></tr>
                  <tr className="bg-muted/30"><td className="sticky left-0 z-10 bg-muted/30 px-3 py-1.5 whitespace-nowrap">GT-R (Series 1)</td><td className="px-1 py-1.5 text-center tabular-nums"><span>47</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>19</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>345</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>412</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>208</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>65</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>66</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>941</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>606</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-3 py-1.5 text-right font-bold">2,709</td></tr>
                  <tr className="bg-card"><td className="sticky left-0 z-10 bg-card px-3 py-1.5 whitespace-nowrap">V-Spec</td><td className="px-1 py-1.5 text-center tabular-nums"><span>61</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>44</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>522</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>514</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>227</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>282</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>132</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>1,222</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>1,190</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-3 py-1.5 text-right font-bold">4,194</td></tr>
                  <tr className="bg-muted/30"><td className="sticky left-0 z-10 bg-muted/30 px-3 py-1.5 whitespace-nowrap">V-Spec N1</td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>38</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-3 py-1.5 text-right font-bold">38</td></tr>
                  <tr className="bg-card"><td className="sticky left-0 z-10 bg-card px-3 py-1.5 whitespace-nowrap">V-Spec (GB)</td><td className="px-1 py-1.5 text-center tabular-nums"><span>11</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>3</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>10</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>22</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>1</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>34</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-3 py-1.5 text-right font-bold">81</td></tr>
                  <tr className="bg-muted/30"><td className="sticky left-0 z-10 bg-muted/30 px-3 py-1.5 whitespace-nowrap">V-Spec (HK)</td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>1</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>1</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>8</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-3 py-1.5 text-right font-bold">10</td></tr>
                  <tr className="bg-card"><td className="sticky left-0 z-10 bg-card px-3 py-1.5 whitespace-nowrap">V-Spec (NZ)</td><td className="px-1 py-1.5 text-center tabular-nums"><span>1</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>1</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>3</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-3 py-1.5 text-right font-bold">5</td></tr>
                  <tr className="bg-muted/30"><td className="sticky left-0 z-10 bg-muted/30 px-3 py-1.5 whitespace-nowrap">V-Spec (SG)</td><td className="px-1 py-1.5 text-center tabular-nums"><span>2</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>1</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>2</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>1</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>1</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>3</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-3 py-1.5 text-right font-bold">10</td></tr>
                  <tr className="bg-card"><td className="sticky left-0 z-10 bg-card px-3 py-1.5 whitespace-nowrap">Unknown (Series 1)</td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-3 py-1.5 text-right font-bold">19</td></tr>
                  
                  <tr className="bg-secondary"><td className="sticky left-0 z-10 bg-secondary px-3 py-1.5 font-bold text-[10px] uppercase tracking-wider">Series 2</td><td colSpan="14"></td><td className="px-3 py-1.5 text-right font-bold">4,512</td></tr>
                  <tr className="bg-card"><td className="sticky left-0 z-10 bg-card px-3 py-1.5 whitespace-nowrap">GT-R (Series 2)</td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>167</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>31</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>246</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>196</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>312</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>316</span></td><td className="px-3 py-1.5 text-right font-bold">1,268</td></tr>
                  <tr className="bg-muted/30"><td className="sticky left-0 z-10 bg-muted/30 px-3 py-1.5 whitespace-nowrap">V-Spec II</td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>198</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>44</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>357</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>1</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>303</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>604</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>348</span></td><td className="px-3 py-1.5 text-right font-bold">1,855</td></tr>
                  <tr className="bg-card"><td className="sticky left-0 z-10 bg-card px-3 py-1.5 whitespace-nowrap">V-Spec II N1</td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>18</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-3 py-1.5 text-right font-bold">18</td></tr>
                  <tr className="bg-muted/30"><td className="sticky left-0 z-10 bg-muted/30 px-3 py-1.5 whitespace-nowrap">V-Spec II (NZ)</td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>1</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>1</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-3 py-1.5 text-right font-bold">2</td></tr>
                  <tr className="bg-card"><td className="sticky left-0 z-10 bg-card px-3 py-1.5 whitespace-nowrap">M-Spec</td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>122</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>39</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>93</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>112</span></td><td className="px-3 py-1.5 text-right font-bold">366</td></tr>
                  <tr className="bg-muted/30"><td className="sticky left-0 z-10 bg-muted/30 px-3 py-1.5 whitespace-nowrap">V-Spec II Nür</td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>62</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>156</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>159</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>141</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>119</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>81</span></td><td className="px-3 py-1.5 text-right font-bold">718</td></tr>
                  <tr className="bg-card"><td className="sticky left-0 z-10 bg-card px-3 py-1.5 whitespace-nowrap">M-Spec Nür</td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>9</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>24</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>144</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>75</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span className="text-muted-foreground/40">–</span></td><td className="px-1 py-1.5 text-center tabular-nums"><span>33</span></td><td className="px-3 py-1.5 text-right font-bold">285</td></tr>
                  
                  <tr className="border-t border-border bg-secondary"><td className="sticky left-0 z-10 bg-secondary px-3 py-2 font-bold text-[10px] uppercase tracking-wider">By Colour</td><td className="px-1 py-2 text-center font-bold tabular-nums">122</td><td className="px-1 py-2 text-center font-bold tabular-nums">68</td><td className="px-1 py-2 text-center font-bold tabular-nums">131</td><td className="px-1 py-2 text-center font-bold tabular-nums">1,370</td><td className="px-1 py-2 text-center font-bold tabular-nums">300</td><td className="px-1 py-2 text-center font-bold tabular-nums">927</td><td className="px-1 py-2 text-center font-bold tabular-nums">533</td><td className="px-1 py-2 text-center font-bold tabular-nums">347</td><td className="px-1 py-2 text-center font-bold tabular-nums">199</td><td className="px-1 py-2 text-center font-bold tabular-nums">2,983</td><td className="px-1 py-2 text-center font-bold tabular-nums">1</td><td className="px-1 py-2 text-center font-bold tabular-nums">808</td><td className="px-1 py-2 text-center font-bold tabular-nums">2,880</td><td className="px-1 py-2 text-center font-bold tabular-nums">890</td><td className="px-3 py-2 text-right font-bold">11,559</td></tr>
                  <tr className="bg-background"><td className="sticky left-0 z-10 bg-background px-3 py-1 text-muted-foreground text-[10px]">%</td><td className="px-1 py-1 text-center text-[10px] text-muted-foreground tabular-nums">1.1%</td><td className="px-1 py-1 text-center text-[10px] text-muted-foreground tabular-nums">&lt;1%</td><td className="px-1 py-1 text-center text-[10px] text-muted-foreground tabular-nums">1.1%</td><td className="px-1 py-1 text-center text-[10px] text-muted-foreground tabular-nums">11.8%</td><td className="px-1 py-1 text-center text-[10px] text-muted-foreground tabular-nums">2.6%</td><td className="px-1 py-1 text-center text-[10px] text-muted-foreground tabular-nums">8.0%</td><td className="px-1 py-1 text-center text-[10px] text-muted-foreground tabular-nums">4.6%</td><td className="px-1 py-1 text-center text-[10px] text-muted-foreground tabular-nums">3.0%</td><td className="px-1 py-1 text-center text-[10px] text-muted-foreground tabular-nums">1.7%</td><td className="px-1 py-1 text-center text-[10px] text-muted-foreground tabular-nums">25.8%</td><td className="px-1 py-1 text-center text-[10px] text-muted-foreground tabular-nums">&lt;1%</td><td className="px-1 py-1 text-center text-[10px] text-muted-foreground tabular-nums">7.0%</td><td className="px-1 py-1 text-center text-[10px] text-muted-foreground tabular-nums">24.9%</td><td className="px-1 py-1 text-center text-[10px] text-muted-foreground tabular-nums">7.7%</td><td className="px-3 py-1 text-right text-[10px] text-muted-foreground">99.84%</td></tr>
                </tbody>
              </table>
            </div>
          </div>
          <div className="mt-8">
            <h3 className="text-xs font-mono uppercase tracking-widest text-muted-foreground mb-4">Color Legend</h3>
            <div className="flex flex-wrap gap-3">
              <div className="flex items-center gap-1.5"><div className="h-3 w-3 border border-foreground/10" style={{ background: 'rgb(204, 43, 30)' }}></div><span className="font-mono text-[10px] font-medium">AR2</span><span className="text-[10px] text-muted-foreground">Active Red</span></div>
              <div className="flex items-center gap-1.5"><div className="h-3 w-3 border border-foreground/10" style={{ background: 'rgb(245, 208, 0)' }}></div><span className="font-mono text-[10px] font-medium">EV1</span><span className="text-[10px] text-muted-foreground">Lightning Yellow</span></div>
              <div className="flex items-center gap-1.5"><div className="h-3 w-3 border border-foreground/10" style={{ background: 'rgb(138, 122, 60)' }}></div><span className="font-mono text-[10px] font-medium">EY0</span><span className="text-[10px] text-muted-foreground">Silica Brass</span></div>
              <div className="flex items-center gap-1.5"><div className="h-3 w-3 border border-foreground/10" style={{ background: 'rgb(42, 42, 42)' }}></div><span className="font-mono text-[10px] font-medium">GV1</span><span className="text-[10px] text-muted-foreground">Black Pearl</span></div>
              <div className="flex items-center gap-1.5"><div className="h-3 w-3 border border-foreground/10" style={{ background: 'rgb(45, 92, 60)' }}></div><span className="font-mono text-[10px] font-medium">JW0</span><span className="text-[10px] text-muted-foreground">Millennium Jade</span></div>
              <div className="flex items-center gap-1.5"><div className="h-3 w-3 border border-foreground/10" style={{ background: 'rgb(176, 176, 176)' }}></div><span className="font-mono text-[10px] font-medium">KR4</span><span className="text-[10px] text-muted-foreground">Sonic Silver</span></div>
              <div className="flex items-center gap-1.5"><div className="h-3 w-3 border border-foreground/10" style={{ background: 'rgb(154, 172, 184)' }}></div><span className="font-mono text-[10px] font-medium">KV2</span><span className="text-[10px] text-muted-foreground">Athlete Silver</span></div>
              <div className="flex items-center gap-1.5"><div className="h-3 w-3 border border-foreground/10" style={{ background: 'rgb(123, 79, 140)' }}></div><span className="font-mono text-[10px] font-medium">LV4</span><span className="text-[10px] text-muted-foreground">Midnight Purple II</span></div>
              <div className="flex items-center gap-1.5"><div className="h-3 w-3 border border-foreground/10" style={{ background: 'rgb(90, 58, 122)' }}></div><span className="font-mono text-[10px] font-medium">LX0</span><span className="text-[10px] text-muted-foreground">Midnight Purple III</span></div>
              <div className="flex items-center gap-1.5"><div className="h-3 w-3 border border-foreground/10" style={{ background: 'rgb(240, 240, 240)' }}></div><span className="font-mono text-[10px] font-medium">QM1</span><span className="text-[10px] text-muted-foreground">White</span></div>
              <div className="flex items-center gap-1.5"><div className="h-3 w-3 border border-foreground/10" style={{ background: 'rgb(232, 224, 208)' }}></div><span className="font-mono text-[10px] font-medium">QT1</span><span className="text-[10px] text-muted-foreground">Pearl White</span></div>
              <div className="flex items-center gap-1.5"><div className="h-3 w-3 border border-foreground/10" style={{ background: 'rgb(220, 220, 208)' }}></div><span className="font-mono text-[10px] font-medium">QX1</span><span className="text-[10px] text-muted-foreground">Pearl White</span></div>
              <div className="flex items-center gap-1.5"><div className="h-3 w-3 border border-foreground/10" style={{ background: 'rgb(58, 108, 176)' }}></div><span className="font-mono text-[10px] font-medium">TV2</span><span className="text-[10px] text-muted-foreground">Bayside Blue</span></div>
              <div className="flex items-center gap-1.5"><div className="h-3 w-3 border border-foreground/10" style={{ background: 'rgb(192, 192, 184)' }}></div><span className="font-mono text-[10px] font-medium">WV2</span><span className="text-[10px] text-muted-foreground">Sparkling Silver</span></div>
            </div>
          </div>
          <p className="mt-6 text-xs text-muted-foreground italic font-mono">By-colour total 11,559 + Unknown(S1)=19 = 11,578.</p>
        </div>
      </div>
    </div>
  );
}
